### ISSUE TITLE
date 0000-00-00 from mysql default null not supported

### ISSUE THREAD

**Issue by dpavlin** [duckdb/duckdb_mysql#8] opened 2023-11-11 15:45 UTC
### What happens?

When I try to select data from mysql database I get following error:

Error: Conversion Error: date field value out of range: "0000-00-00", expected format is (YYYY-MM-DD)

### To Reproduce

When mysql has null as default for date, query will return 0000-00-00 as date and generate error above.

### OS:

Linux

### MySQL Version:

5.6.43

### DuckDB Version:

0.9.1

### DuckDB Client:

cli

### Full Name:

Dobrica Pavlinušić

### Affiliation:

rot13

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-11-12 09:20
Thanks for the report!

I cannot reproduce this locally, at least in a later version of MySQL. Could you provide a reproducible example?

**Comment by thbley** [comment] 2023-11-12 17:52
I'm not sure if it's related, older mysql versions (pre 8.x) allowed 0000-00-00 as date:
https://blogs.oracle.com/mysql/post/mysql-80-and-wrong-dates

![Screenshot_20231112_185137](https://github.com/duckdb/duckdb_mysql/assets/941223/9564631d-30b6-4168-b87d-8aaa4718a946)

**Comment by Mytherin** [comment] 2023-11-13 12:17
Looks like this behavior is specific to 5.6 as this has also been fixed in 5.7. I've pushed a fix for this in #11 which just converts invalid values to NULL.

**Closed** 2023-11-13 15:06 UTC
